import type { ReactNode } from 'react';
import type { FormSchema, FormStep, Field } from '../../model/schema/form-schema';
import type { FieldErrors } from '../../model/engines/validation-engine';
export type FormStepCardProps = {
  schema: FormSchema;
  step: FormStep;
  stepIndex: number;
  stepsCount: number;
  values: Record<string, unknown>;
  fieldErrors?: FieldErrors;
  touched?: Record<string, boolean>;
  onFieldChange?: (name: string, value: unknown) => void;
  onNext?: () => void;
  onBack?: () => void;
  onSkip?: () => void;
  nextLabel?: string;
  allowDraft?: boolean;
  onSaveDraft?: () => void;
  isLastStep?: boolean;
  onSubmit?: () => void;
  submitLabel?: string;
  embedded?: boolean;
  slotBeforeActions?: ReactNode;
  hideStepHeader?: boolean;
  showAllFields?: boolean;
  renderFieldDecorator?: (field: Field, cell: ReactNode) => ReactNode;
};
