import {
  CategoryClipboardSolid,
  CategoryColorSolid,
  DocumentsDocsSolid,
  DocumentsFolderSolid,
  SecurityLockSolid,
  ServiceDragSolid,
  ServiceEyeSolid,
  ServicePlaySolid,
  ServicePlusCircleSolid,
  ServicePlusSolid,
  ServiceStructureSolid,
  SystemCloudUploadSolid,
  SystemDeleteSolid,
  SystemDownloadSolid,
  SystemEditSolid,
  SystemExportSolid,
  SystemImportSolid,
  SystemNotificationsSolid,
  SystemSaveSolid,
  SystemSettingsSolid,
  SystemSmallArrowDownSolid,
  SystemSmallArrowUpSolid,
  SystemUploadSolid,
} from '@admiral-ds/icons';
import type { IconComponent } from './types';
export const APP_UI_ICONS = {
  logo: DocumentsDocsSolid,
  builder: SystemEditSolid,
  runtime: ServicePlaySolid,
  save: SystemSaveSolid,
  export: SystemExportSolid,
  import: SystemImportSolid,
  upload: SystemUploadSolid,
  download: SystemDownloadSolid,
  newForm: ServicePlusSolid,
  settings: SystemSettingsSolid,
  palette: CategoryColorSolid,
  canvas: ServiceStructureSolid,
  addStep: ServicePlusCircleSolid,
  arrowUp: SystemSmallArrowUpSolid,
  arrowDown: SystemSmallArrowDownSolid,
  delete: SystemDeleteSolid,
  drag: ServiceDragSolid,
  drop: SystemCloudUploadSolid,
  preview: ServiceEyeSolid,
  lock: SecurityLockSolid,
  workspace: DocumentsFolderSolid,
  templates: CategoryClipboardSolid,
  whatsNew: SystemNotificationsSolid,
  archive: SystemDeleteSolid,
} as const satisfies Record<string, IconComponent>;
export type AppUiIconKey = keyof typeof APP_UI_ICONS;
